/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStrategiesRouteImport } from './routes/_authenticated/strategies'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPatternsRouteImport } from './routes/_authenticated/patterns'
import { Route as AuthenticatedPatternPerformanceRouteImport } from './routes/_authenticated/pattern-performance'
import { Route as AuthenticatedModelValidationRouteImport } from './routes/_authenticated/model-validation'
import { Route as AuthenticatedLiveRouteImport } from './routes/_authenticated/live'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBacktestRouteImport } from './routes/_authenticated/backtest'
import { Route as AuthenticatedAnalyzeRouteImport } from './routes/_authenticated/analyze'
import { Route as AuthenticatedAnalysisIdRouteImport } from './routes/_authenticated/analysis.$id'
import { Route as ApiPublicHooksCaptureClosingOddsRouteImport } from './routes/api/public/hooks/capture-closing-odds'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStrategiesRoute = AuthenticatedStrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPatternsRoute = AuthenticatedPatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPatternPerformanceRoute =
  AuthenticatedPatternPerformanceRouteImport.update({
    id: '/pattern-performance',
    path: '/pattern-performance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedModelValidationRoute =
  AuthenticatedModelValidationRouteImport.update({
    id: '/model-validation',
    path: '/model-validation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLiveRoute = AuthenticatedLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBacktestRoute = AuthenticatedBacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyzeRoute = AuthenticatedAnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalysisIdRoute = AuthenticatedAnalysisIdRouteImport.update({
  id: '/analysis/$id',
  path: '/analysis/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicHooksCaptureClosingOddsRoute =
  ApiPublicHooksCaptureClosingOddsRouteImport.update({
    id: '/api/public/hooks/capture-closing-odds',
    path: '/api/public/hooks/capture-closing-odds',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/analyze': typeof AuthenticatedAnalyzeRoute
  '/backtest': typeof AuthenticatedBacktestRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/live': typeof AuthenticatedLiveRoute
  '/model-validation': typeof AuthenticatedModelValidationRoute
  '/pattern-performance': typeof AuthenticatedPatternPerformanceRoute
  '/patterns': typeof AuthenticatedPatternsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/strategies': typeof AuthenticatedStrategiesRoute
  '/analysis/$id': typeof AuthenticatedAnalysisIdRoute
  '/api/public/hooks/capture-closing-odds': typeof ApiPublicHooksCaptureClosingOddsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/analyze': typeof AuthenticatedAnalyzeRoute
  '/backtest': typeof AuthenticatedBacktestRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/live': typeof AuthenticatedLiveRoute
  '/model-validation': typeof AuthenticatedModelValidationRoute
  '/pattern-performance': typeof AuthenticatedPatternPerformanceRoute
  '/patterns': typeof AuthenticatedPatternsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/strategies': typeof AuthenticatedStrategiesRoute
  '/analysis/$id': typeof AuthenticatedAnalysisIdRoute
  '/api/public/hooks/capture-closing-odds': typeof ApiPublicHooksCaptureClosingOddsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/analyze': typeof AuthenticatedAnalyzeRoute
  '/_authenticated/backtest': typeof AuthenticatedBacktestRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/live': typeof AuthenticatedLiveRoute
  '/_authenticated/model-validation': typeof AuthenticatedModelValidationRoute
  '/_authenticated/pattern-performance': typeof AuthenticatedPatternPerformanceRoute
  '/_authenticated/patterns': typeof AuthenticatedPatternsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/strategies': typeof AuthenticatedStrategiesRoute
  '/_authenticated/analysis/$id': typeof AuthenticatedAnalysisIdRoute
  '/api/public/hooks/capture-closing-odds': typeof ApiPublicHooksCaptureClosingOddsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/analyze'
    | '/backtest'
    | '/dashboard'
    | '/history'
    | '/live'
    | '/model-validation'
    | '/pattern-performance'
    | '/patterns'
    | '/settings'
    | '/strategies'
    | '/analysis/$id'
    | '/api/public/hooks/capture-closing-odds'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/analyze'
    | '/backtest'
    | '/dashboard'
    | '/history'
    | '/live'
    | '/model-validation'
    | '/pattern-performance'
    | '/patterns'
    | '/settings'
    | '/strategies'
    | '/analysis/$id'
    | '/api/public/hooks/capture-closing-odds'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/analyze'
    | '/_authenticated/backtest'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/live'
    | '/_authenticated/model-validation'
    | '/_authenticated/pattern-performance'
    | '/_authenticated/patterns'
    | '/_authenticated/settings'
    | '/_authenticated/strategies'
    | '/_authenticated/analysis/$id'
    | '/api/public/hooks/capture-closing-odds'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiPublicHooksCaptureClosingOddsRoute: typeof ApiPublicHooksCaptureClosingOddsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/strategies': {
      id: '/_authenticated/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof AuthenticatedStrategiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patterns': {
      id: '/_authenticated/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof AuthenticatedPatternsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pattern-performance': {
      id: '/_authenticated/pattern-performance'
      path: '/pattern-performance'
      fullPath: '/pattern-performance'
      preLoaderRoute: typeof AuthenticatedPatternPerformanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/model-validation': {
      id: '/_authenticated/model-validation'
      path: '/model-validation'
      fullPath: '/model-validation'
      preLoaderRoute: typeof AuthenticatedModelValidationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/live': {
      id: '/_authenticated/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AuthenticatedLiveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/backtest': {
      id: '/_authenticated/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof AuthenticatedBacktestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analyze': {
      id: '/_authenticated/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AuthenticatedAnalyzeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analysis/$id': {
      id: '/_authenticated/analysis/$id'
      path: '/analysis/$id'
      fullPath: '/analysis/$id'
      preLoaderRoute: typeof AuthenticatedAnalysisIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hooks/capture-closing-odds': {
      id: '/api/public/hooks/capture-closing-odds'
      path: '/api/public/hooks/capture-closing-odds'
      fullPath: '/api/public/hooks/capture-closing-odds'
      preLoaderRoute: typeof ApiPublicHooksCaptureClosingOddsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyzeRoute: typeof AuthenticatedAnalyzeRoute
  AuthenticatedBacktestRoute: typeof AuthenticatedBacktestRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedLiveRoute: typeof AuthenticatedLiveRoute
  AuthenticatedModelValidationRoute: typeof AuthenticatedModelValidationRoute
  AuthenticatedPatternPerformanceRoute: typeof AuthenticatedPatternPerformanceRoute
  AuthenticatedPatternsRoute: typeof AuthenticatedPatternsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStrategiesRoute: typeof AuthenticatedStrategiesRoute
  AuthenticatedAnalysisIdRoute: typeof AuthenticatedAnalysisIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyzeRoute: AuthenticatedAnalyzeRoute,
  AuthenticatedBacktestRoute: AuthenticatedBacktestRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedLiveRoute: AuthenticatedLiveRoute,
  AuthenticatedModelValidationRoute: AuthenticatedModelValidationRoute,
  AuthenticatedPatternPerformanceRoute: AuthenticatedPatternPerformanceRoute,
  AuthenticatedPatternsRoute: AuthenticatedPatternsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStrategiesRoute: AuthenticatedStrategiesRoute,
  AuthenticatedAnalysisIdRoute: AuthenticatedAnalysisIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiPublicHooksCaptureClosingOddsRoute: ApiPublicHooksCaptureClosingOddsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
