/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAnalyzeRouteImport } from './routes/_authenticated/analyze'
import { Route as AuthenticatedBacktestRouteImport } from './routes/_authenticated/backtest'
import { Route as AuthenticatedChartRouteImport } from './routes/_authenticated/chart'
import { Route as AuthenticatedCryptoRouteImport } from './routes/_authenticated/crypto'
import { Route as AuthenticatedCryptoPaperRouteImport } from './routes/_authenticated/crypto-paper'
import { Route as AuthenticatedCryptoSandboxRouteImport } from './routes/_authenticated/crypto-sandbox'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedLiveRouteImport } from './routes/_authenticated/live'
import { Route as AuthenticatedModelValidationRouteImport } from './routes/_authenticated/model-validation'
import { Route as AuthenticatedOpsManualRouteImport } from './routes/_authenticated/ops-manual'
import { Route as AuthenticatedPatternPerformanceRouteImport } from './routes/_authenticated/pattern-performance'
import { Route as AuthenticatedPatternsRouteImport } from './routes/_authenticated/patterns'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStrategiesRouteImport } from './routes/_authenticated/strategies'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthenticatedAnalysisIdRouteImport } from './routes/_authenticated/analysis.$id'
import { Route as ApiHealthKalshiRouteImport } from './routes/api/health/kalshi'
import { Route as ApiPublicSendDailyDigestsRouteImport } from './routes/api/public/send-daily-digests'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicHooksAutoModelBetTickRouteImport } from './routes/api/public/hooks/auto-model-bet-tick'
import { Route as ApiPublicHooksAutoOddsTickRouteImport } from './routes/api/public/hooks/auto-odds-tick'
import { Route as ApiPublicHooksAutoTradeRouteImport } from './routes/api/public/hooks/auto-trade'
import { Route as ApiPublicHooksBackfillOutcomesRouteImport } from './routes/api/public/hooks/backfill-outcomes'
import { Route as ApiPublicHooksBackfillTripleWindowRouteImport } from './routes/api/public/hooks/backfill-triple-window'
import { Route as ApiPublicHooksBigFlipTickRouteImport } from './routes/api/public/hooks/big-flip-tick'
import { Route as ApiPublicHooksBtcCalibrateRouteImport } from './routes/api/public/hooks/btc-calibrate'
import { Route as ApiPublicHooksBtcSnapshotTickRouteImport } from './routes/api/public/hooks/btc-snapshot-tick'
import { Route as ApiPublicHooksCandlesIngestRouteImport } from './routes/api/public/hooks/candles-ingest'
import { Route as ApiPublicHooksCaptureClosingOddsRouteImport } from './routes/api/public/hooks/capture-closing-odds'
import { Route as ApiPublicHooksCryptoStudyRouteImport } from './routes/api/public/hooks/crypto-study'
import { Route as ApiPublicHooksKalshiBookTickRouteImport } from './routes/api/public/hooks/kalshi-book-tick'
import { Route as ApiPublicHooksMarketContextTickRouteImport } from './routes/api/public/hooks/market-context-tick'
import { Route as ApiPublicHooksMarketIntelMatchRouteImport } from './routes/api/public/hooks/market-intel-match'
import { Route as ApiPublicHooksMartingaleTickRouteImport } from './routes/api/public/hooks/martingale-tick'
import { Route as ApiPublicHooksMultiTfShadowRouteImport } from './routes/api/public/hooks/multi-tf-shadow'
import { Route as ApiPublicHooksOddsShadowTickRouteImport } from './routes/api/public/hooks/odds-shadow-tick'
import { Route as ApiPublicHooksOpsDailyBacktestRouteImport } from './routes/api/public/hooks/ops-daily-backtest'
import { Route as ApiPublicHooksPinRiskShadowTickRouteImport } from './routes/api/public/hooks/pin-risk-shadow-tick'
import { Route as ApiPublicHooksRecomputePredictionsRouteImport } from './routes/api/public/hooks/recompute-predictions'
import { Route as ApiPublicHooksSettleBtcPredictionsRouteImport } from './routes/api/public/hooks/settle-btc-predictions'
import { Route as ApiPublicHooksStudyAutoLiveTickRouteImport } from './routes/api/public/hooks/study-auto-live-tick'
import { Route as ApiPublicHooksStudyLockTickRouteImport } from './routes/api/public/hooks/study-lock-tick'
import { Route as ApiPublicHooksTripleWindowTickRouteImport } from './routes/api/public/hooks/triple-window-tick'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyzeRoute = AuthenticatedAnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBacktestRoute = AuthenticatedBacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChartRoute = AuthenticatedChartRouteImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCryptoRoute = AuthenticatedCryptoRouteImport.update({
  id: '/crypto',
  path: '/crypto',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCryptoPaperRoute =
  AuthenticatedCryptoPaperRouteImport.update({
    id: '/crypto-paper',
    path: '/crypto-paper',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCryptoSandboxRoute =
  AuthenticatedCryptoSandboxRouteImport.update({
    id: '/crypto-sandbox',
    path: '/crypto-sandbox',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLiveRoute = AuthenticatedLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedModelValidationRoute =
  AuthenticatedModelValidationRouteImport.update({
    id: '/model-validation',
    path: '/model-validation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOpsManualRoute = AuthenticatedOpsManualRouteImport.update({
  id: '/ops-manual',
  path: '/ops-manual',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPatternPerformanceRoute =
  AuthenticatedPatternPerformanceRouteImport.update({
    id: '/pattern-performance',
    path: '/pattern-performance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatternsRoute = AuthenticatedPatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStrategiesRoute = AuthenticatedStrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalysisIdRoute = AuthenticatedAnalysisIdRouteImport.update({
  id: '/analysis/$id',
  path: '/analysis/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiHealthKalshiRoute = ApiHealthKalshiRouteImport.update({
  id: '/api/health/kalshi',
  path: '/api/health/kalshi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendDailyDigestsRoute =
  ApiPublicSendDailyDigestsRouteImport.update({
    id: '/api/public/send-daily-digests',
    path: '/api/public/send-daily-digests',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAutoModelBetTickRoute =
  ApiPublicHooksAutoModelBetTickRouteImport.update({
    id: '/api/public/hooks/auto-model-bet-tick',
    path: '/api/public/hooks/auto-model-bet-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoOddsTickRoute =
  ApiPublicHooksAutoOddsTickRouteImport.update({
    id: '/api/public/hooks/auto-odds-tick',
    path: '/api/public/hooks/auto-odds-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoTradeRoute = ApiPublicHooksAutoTradeRouteImport.update({
  id: '/api/public/hooks/auto-trade',
  path: '/api/public/hooks/auto-trade',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksBackfillOutcomesRoute =
  ApiPublicHooksBackfillOutcomesRouteImport.update({
    id: '/api/public/hooks/backfill-outcomes',
    path: '/api/public/hooks/backfill-outcomes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBackfillTripleWindowRoute =
  ApiPublicHooksBackfillTripleWindowRouteImport.update({
    id: '/api/public/hooks/backfill-triple-window',
    path: '/api/public/hooks/backfill-triple-window',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBigFlipTickRoute =
  ApiPublicHooksBigFlipTickRouteImport.update({
    id: '/api/public/hooks/big-flip-tick',
    path: '/api/public/hooks/big-flip-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBtcCalibrateRoute =
  ApiPublicHooksBtcCalibrateRouteImport.update({
    id: '/api/public/hooks/btc-calibrate',
    path: '/api/public/hooks/btc-calibrate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBtcSnapshotTickRoute =
  ApiPublicHooksBtcSnapshotTickRouteImport.update({
    id: '/api/public/hooks/btc-snapshot-tick',
    path: '/api/public/hooks/btc-snapshot-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCandlesIngestRoute =
  ApiPublicHooksCandlesIngestRouteImport.update({
    id: '/api/public/hooks/candles-ingest',
    path: '/api/public/hooks/candles-ingest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCaptureClosingOddsRoute =
  ApiPublicHooksCaptureClosingOddsRouteImport.update({
    id: '/api/public/hooks/capture-closing-odds',
    path: '/api/public/hooks/capture-closing-odds',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCryptoStudyRoute =
  ApiPublicHooksCryptoStudyRouteImport.update({
    id: '/api/public/hooks/crypto-study',
    path: '/api/public/hooks/crypto-study',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksKalshiBookTickRoute =
  ApiPublicHooksKalshiBookTickRouteImport.update({
    id: '/api/public/hooks/kalshi-book-tick',
    path: '/api/public/hooks/kalshi-book-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMarketContextTickRoute =
  ApiPublicHooksMarketContextTickRouteImport.update({
    id: '/api/public/hooks/market-context-tick',
    path: '/api/public/hooks/market-context-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMarketIntelMatchRoute =
  ApiPublicHooksMarketIntelMatchRouteImport.update({
    id: '/api/public/hooks/market-intel-match',
    path: '/api/public/hooks/market-intel-match',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMartingaleTickRoute =
  ApiPublicHooksMartingaleTickRouteImport.update({
    id: '/api/public/hooks/martingale-tick',
    path: '/api/public/hooks/martingale-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMultiTfShadowRoute =
  ApiPublicHooksMultiTfShadowRouteImport.update({
    id: '/api/public/hooks/multi-tf-shadow',
    path: '/api/public/hooks/multi-tf-shadow',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksOddsShadowTickRoute =
  ApiPublicHooksOddsShadowTickRouteImport.update({
    id: '/api/public/hooks/odds-shadow-tick',
    path: '/api/public/hooks/odds-shadow-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksOpsDailyBacktestRoute =
  ApiPublicHooksOpsDailyBacktestRouteImport.update({
    id: '/api/public/hooks/ops-daily-backtest',
    path: '/api/public/hooks/ops-daily-backtest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPinRiskShadowTickRoute =
  ApiPublicHooksPinRiskShadowTickRouteImport.update({
    id: '/api/public/hooks/pin-risk-shadow-tick',
    path: '/api/public/hooks/pin-risk-shadow-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRecomputePredictionsRoute =
  ApiPublicHooksRecomputePredictionsRouteImport.update({
    id: '/api/public/hooks/recompute-predictions',
    path: '/api/public/hooks/recompute-predictions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSettleBtcPredictionsRoute =
  ApiPublicHooksSettleBtcPredictionsRouteImport.update({
    id: '/api/public/hooks/settle-btc-predictions',
    path: '/api/public/hooks/settle-btc-predictions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksStudyAutoLiveTickRoute =
  ApiPublicHooksStudyAutoLiveTickRouteImport.update({
    id: '/api/public/hooks/study-auto-live-tick',
    path: '/api/public/hooks/study-auto-live-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksStudyLockTickRoute =
  ApiPublicHooksStudyLockTickRouteImport.update({
    id: '/api/public/hooks/study-lock-tick',
    path: '/api/public/hooks/study-lock-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTripleWindowTickRoute =
  ApiPublicHooksTripleWindowTickRouteImport.update({
    id: '/api/public/hooks/triple-window-tick',
    path: '/api/public/hooks/triple-window-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analyze': typeof AuthenticatedAnalyzeRoute
  '/backtest': typeof AuthenticatedBacktestRoute
  '/chart': typeof AuthenticatedChartRoute
  '/crypto': typeof AuthenticatedCryptoRoute
  '/crypto-paper': typeof AuthenticatedCryptoPaperRoute
  '/crypto-sandbox': typeof AuthenticatedCryptoSandboxRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/live': typeof AuthenticatedLiveRoute
  '/model-validation': typeof AuthenticatedModelValidationRoute
  '/ops-manual': typeof AuthenticatedOpsManualRoute
  '/pattern-performance': typeof AuthenticatedPatternPerformanceRoute
  '/patterns': typeof AuthenticatedPatternsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/strategies': typeof AuthenticatedStrategiesRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/analysis/$id': typeof AuthenticatedAnalysisIdRoute
  '/api/health/kalshi': typeof ApiHealthKalshiRoute
  '/api/public/send-daily-digests': typeof ApiPublicSendDailyDigestsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/auto-model-bet-tick': typeof ApiPublicHooksAutoModelBetTickRoute
  '/api/public/hooks/auto-odds-tick': typeof ApiPublicHooksAutoOddsTickRoute
  '/api/public/hooks/auto-trade': typeof ApiPublicHooksAutoTradeRoute
  '/api/public/hooks/backfill-outcomes': typeof ApiPublicHooksBackfillOutcomesRoute
  '/api/public/hooks/backfill-triple-window': typeof ApiPublicHooksBackfillTripleWindowRoute
  '/api/public/hooks/big-flip-tick': typeof ApiPublicHooksBigFlipTickRoute
  '/api/public/hooks/btc-calibrate': typeof ApiPublicHooksBtcCalibrateRoute
  '/api/public/hooks/btc-snapshot-tick': typeof ApiPublicHooksBtcSnapshotTickRoute
  '/api/public/hooks/candles-ingest': typeof ApiPublicHooksCandlesIngestRoute
  '/api/public/hooks/capture-closing-odds': typeof ApiPublicHooksCaptureClosingOddsRoute
  '/api/public/hooks/crypto-study': typeof ApiPublicHooksCryptoStudyRoute
  '/api/public/hooks/kalshi-book-tick': typeof ApiPublicHooksKalshiBookTickRoute
  '/api/public/hooks/market-context-tick': typeof ApiPublicHooksMarketContextTickRoute
  '/api/public/hooks/market-intel-match': typeof ApiPublicHooksMarketIntelMatchRoute
  '/api/public/hooks/martingale-tick': typeof ApiPublicHooksMartingaleTickRoute
  '/api/public/hooks/multi-tf-shadow': typeof ApiPublicHooksMultiTfShadowRoute
  '/api/public/hooks/odds-shadow-tick': typeof ApiPublicHooksOddsShadowTickRoute
  '/api/public/hooks/ops-daily-backtest': typeof ApiPublicHooksOpsDailyBacktestRoute
  '/api/public/hooks/pin-risk-shadow-tick': typeof ApiPublicHooksPinRiskShadowTickRoute
  '/api/public/hooks/recompute-predictions': typeof ApiPublicHooksRecomputePredictionsRoute
  '/api/public/hooks/settle-btc-predictions': typeof ApiPublicHooksSettleBtcPredictionsRoute
  '/api/public/hooks/study-auto-live-tick': typeof ApiPublicHooksStudyAutoLiveTickRoute
  '/api/public/hooks/study-lock-tick': typeof ApiPublicHooksStudyLockTickRoute
  '/api/public/hooks/triple-window-tick': typeof ApiPublicHooksTripleWindowTickRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analyze': typeof AuthenticatedAnalyzeRoute
  '/backtest': typeof AuthenticatedBacktestRoute
  '/chart': typeof AuthenticatedChartRoute
  '/crypto': typeof AuthenticatedCryptoRoute
  '/crypto-paper': typeof AuthenticatedCryptoPaperRoute
  '/crypto-sandbox': typeof AuthenticatedCryptoSandboxRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/live': typeof AuthenticatedLiveRoute
  '/model-validation': typeof AuthenticatedModelValidationRoute
  '/ops-manual': typeof AuthenticatedOpsManualRoute
  '/pattern-performance': typeof AuthenticatedPatternPerformanceRoute
  '/patterns': typeof AuthenticatedPatternsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/strategies': typeof AuthenticatedStrategiesRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/analysis/$id': typeof AuthenticatedAnalysisIdRoute
  '/api/health/kalshi': typeof ApiHealthKalshiRoute
  '/api/public/send-daily-digests': typeof ApiPublicSendDailyDigestsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/auto-model-bet-tick': typeof ApiPublicHooksAutoModelBetTickRoute
  '/api/public/hooks/auto-odds-tick': typeof ApiPublicHooksAutoOddsTickRoute
  '/api/public/hooks/auto-trade': typeof ApiPublicHooksAutoTradeRoute
  '/api/public/hooks/backfill-outcomes': typeof ApiPublicHooksBackfillOutcomesRoute
  '/api/public/hooks/backfill-triple-window': typeof ApiPublicHooksBackfillTripleWindowRoute
  '/api/public/hooks/big-flip-tick': typeof ApiPublicHooksBigFlipTickRoute
  '/api/public/hooks/btc-calibrate': typeof ApiPublicHooksBtcCalibrateRoute
  '/api/public/hooks/btc-snapshot-tick': typeof ApiPublicHooksBtcSnapshotTickRoute
  '/api/public/hooks/candles-ingest': typeof ApiPublicHooksCandlesIngestRoute
  '/api/public/hooks/capture-closing-odds': typeof ApiPublicHooksCaptureClosingOddsRoute
  '/api/public/hooks/crypto-study': typeof ApiPublicHooksCryptoStudyRoute
  '/api/public/hooks/kalshi-book-tick': typeof ApiPublicHooksKalshiBookTickRoute
  '/api/public/hooks/market-context-tick': typeof ApiPublicHooksMarketContextTickRoute
  '/api/public/hooks/market-intel-match': typeof ApiPublicHooksMarketIntelMatchRoute
  '/api/public/hooks/martingale-tick': typeof ApiPublicHooksMartingaleTickRoute
  '/api/public/hooks/multi-tf-shadow': typeof ApiPublicHooksMultiTfShadowRoute
  '/api/public/hooks/odds-shadow-tick': typeof ApiPublicHooksOddsShadowTickRoute
  '/api/public/hooks/ops-daily-backtest': typeof ApiPublicHooksOpsDailyBacktestRoute
  '/api/public/hooks/pin-risk-shadow-tick': typeof ApiPublicHooksPinRiskShadowTickRoute
  '/api/public/hooks/recompute-predictions': typeof ApiPublicHooksRecomputePredictionsRoute
  '/api/public/hooks/settle-btc-predictions': typeof ApiPublicHooksSettleBtcPredictionsRoute
  '/api/public/hooks/study-auto-live-tick': typeof ApiPublicHooksStudyAutoLiveTickRoute
  '/api/public/hooks/study-lock-tick': typeof ApiPublicHooksStudyLockTickRoute
  '/api/public/hooks/triple-window-tick': typeof ApiPublicHooksTripleWindowTickRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/analyze': typeof AuthenticatedAnalyzeRoute
  '/_authenticated/backtest': typeof AuthenticatedBacktestRoute
  '/_authenticated/chart': typeof AuthenticatedChartRoute
  '/_authenticated/crypto': typeof AuthenticatedCryptoRoute
  '/_authenticated/crypto-paper': typeof AuthenticatedCryptoPaperRoute
  '/_authenticated/crypto-sandbox': typeof AuthenticatedCryptoSandboxRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/live': typeof AuthenticatedLiveRoute
  '/_authenticated/model-validation': typeof AuthenticatedModelValidationRoute
  '/_authenticated/ops-manual': typeof AuthenticatedOpsManualRoute
  '/_authenticated/pattern-performance': typeof AuthenticatedPatternPerformanceRoute
  '/_authenticated/patterns': typeof AuthenticatedPatternsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/strategies': typeof AuthenticatedStrategiesRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/_authenticated/analysis/$id': typeof AuthenticatedAnalysisIdRoute
  '/api/health/kalshi': typeof ApiHealthKalshiRoute
  '/api/public/send-daily-digests': typeof ApiPublicSendDailyDigestsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/auto-model-bet-tick': typeof ApiPublicHooksAutoModelBetTickRoute
  '/api/public/hooks/auto-odds-tick': typeof ApiPublicHooksAutoOddsTickRoute
  '/api/public/hooks/auto-trade': typeof ApiPublicHooksAutoTradeRoute
  '/api/public/hooks/backfill-outcomes': typeof ApiPublicHooksBackfillOutcomesRoute
  '/api/public/hooks/backfill-triple-window': typeof ApiPublicHooksBackfillTripleWindowRoute
  '/api/public/hooks/big-flip-tick': typeof ApiPublicHooksBigFlipTickRoute
  '/api/public/hooks/btc-calibrate': typeof ApiPublicHooksBtcCalibrateRoute
  '/api/public/hooks/btc-snapshot-tick': typeof ApiPublicHooksBtcSnapshotTickRoute
  '/api/public/hooks/candles-ingest': typeof ApiPublicHooksCandlesIngestRoute
  '/api/public/hooks/capture-closing-odds': typeof ApiPublicHooksCaptureClosingOddsRoute
  '/api/public/hooks/crypto-study': typeof ApiPublicHooksCryptoStudyRoute
  '/api/public/hooks/kalshi-book-tick': typeof ApiPublicHooksKalshiBookTickRoute
  '/api/public/hooks/market-context-tick': typeof ApiPublicHooksMarketContextTickRoute
  '/api/public/hooks/market-intel-match': typeof ApiPublicHooksMarketIntelMatchRoute
  '/api/public/hooks/martingale-tick': typeof ApiPublicHooksMartingaleTickRoute
  '/api/public/hooks/multi-tf-shadow': typeof ApiPublicHooksMultiTfShadowRoute
  '/api/public/hooks/odds-shadow-tick': typeof ApiPublicHooksOddsShadowTickRoute
  '/api/public/hooks/ops-daily-backtest': typeof ApiPublicHooksOpsDailyBacktestRoute
  '/api/public/hooks/pin-risk-shadow-tick': typeof ApiPublicHooksPinRiskShadowTickRoute
  '/api/public/hooks/recompute-predictions': typeof ApiPublicHooksRecomputePredictionsRoute
  '/api/public/hooks/settle-btc-predictions': typeof ApiPublicHooksSettleBtcPredictionsRoute
  '/api/public/hooks/study-auto-live-tick': typeof ApiPublicHooksStudyAutoLiveTickRoute
  '/api/public/hooks/study-lock-tick': typeof ApiPublicHooksStudyLockTickRoute
  '/api/public/hooks/triple-window-tick': typeof ApiPublicHooksTripleWindowTickRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/unsubscribe'
    | '/admin'
    | '/analyze'
    | '/backtest'
    | '/chart'
    | '/crypto'
    | '/crypto-paper'
    | '/crypto-sandbox'
    | '/dashboard'
    | '/history'
    | '/live'
    | '/model-validation'
    | '/ops-manual'
    | '/pattern-performance'
    | '/patterns'
    | '/settings'
    | '/strategies'
    | '/email/unsubscribe'
    | '/analysis/$id'
    | '/api/health/kalshi'
    | '/api/public/send-daily-digests'
    | '/lovable/email/suppression'
    | '/api/public/hooks/auto-model-bet-tick'
    | '/api/public/hooks/auto-odds-tick'
    | '/api/public/hooks/auto-trade'
    | '/api/public/hooks/backfill-outcomes'
    | '/api/public/hooks/backfill-triple-window'
    | '/api/public/hooks/big-flip-tick'
    | '/api/public/hooks/btc-calibrate'
    | '/api/public/hooks/btc-snapshot-tick'
    | '/api/public/hooks/candles-ingest'
    | '/api/public/hooks/capture-closing-odds'
    | '/api/public/hooks/crypto-study'
    | '/api/public/hooks/kalshi-book-tick'
    | '/api/public/hooks/market-context-tick'
    | '/api/public/hooks/market-intel-match'
    | '/api/public/hooks/martingale-tick'
    | '/api/public/hooks/multi-tf-shadow'
    | '/api/public/hooks/odds-shadow-tick'
    | '/api/public/hooks/ops-daily-backtest'
    | '/api/public/hooks/pin-risk-shadow-tick'
    | '/api/public/hooks/recompute-predictions'
    | '/api/public/hooks/settle-btc-predictions'
    | '/api/public/hooks/study-auto-live-tick'
    | '/api/public/hooks/study-lock-tick'
    | '/api/public/hooks/triple-window-tick'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/unsubscribe'
    | '/admin'
    | '/analyze'
    | '/backtest'
    | '/chart'
    | '/crypto'
    | '/crypto-paper'
    | '/crypto-sandbox'
    | '/dashboard'
    | '/history'
    | '/live'
    | '/model-validation'
    | '/ops-manual'
    | '/pattern-performance'
    | '/patterns'
    | '/settings'
    | '/strategies'
    | '/email/unsubscribe'
    | '/analysis/$id'
    | '/api/health/kalshi'
    | '/api/public/send-daily-digests'
    | '/lovable/email/suppression'
    | '/api/public/hooks/auto-model-bet-tick'
    | '/api/public/hooks/auto-odds-tick'
    | '/api/public/hooks/auto-trade'
    | '/api/public/hooks/backfill-outcomes'
    | '/api/public/hooks/backfill-triple-window'
    | '/api/public/hooks/big-flip-tick'
    | '/api/public/hooks/btc-calibrate'
    | '/api/public/hooks/btc-snapshot-tick'
    | '/api/public/hooks/candles-ingest'
    | '/api/public/hooks/capture-closing-odds'
    | '/api/public/hooks/crypto-study'
    | '/api/public/hooks/kalshi-book-tick'
    | '/api/public/hooks/market-context-tick'
    | '/api/public/hooks/market-intel-match'
    | '/api/public/hooks/martingale-tick'
    | '/api/public/hooks/multi-tf-shadow'
    | '/api/public/hooks/odds-shadow-tick'
    | '/api/public/hooks/ops-daily-backtest'
    | '/api/public/hooks/pin-risk-shadow-tick'
    | '/api/public/hooks/recompute-predictions'
    | '/api/public/hooks/settle-btc-predictions'
    | '/api/public/hooks/study-auto-live-tick'
    | '/api/public/hooks/study-lock-tick'
    | '/api/public/hooks/triple-window-tick'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/unsubscribe'
    | '/_authenticated/admin'
    | '/_authenticated/analyze'
    | '/_authenticated/backtest'
    | '/_authenticated/chart'
    | '/_authenticated/crypto'
    | '/_authenticated/crypto-paper'
    | '/_authenticated/crypto-sandbox'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/live'
    | '/_authenticated/model-validation'
    | '/_authenticated/ops-manual'
    | '/_authenticated/pattern-performance'
    | '/_authenticated/patterns'
    | '/_authenticated/settings'
    | '/_authenticated/strategies'
    | '/email/unsubscribe'
    | '/_authenticated/analysis/$id'
    | '/api/health/kalshi'
    | '/api/public/send-daily-digests'
    | '/lovable/email/suppression'
    | '/api/public/hooks/auto-model-bet-tick'
    | '/api/public/hooks/auto-odds-tick'
    | '/api/public/hooks/auto-trade'
    | '/api/public/hooks/backfill-outcomes'
    | '/api/public/hooks/backfill-triple-window'
    | '/api/public/hooks/big-flip-tick'
    | '/api/public/hooks/btc-calibrate'
    | '/api/public/hooks/btc-snapshot-tick'
    | '/api/public/hooks/candles-ingest'
    | '/api/public/hooks/capture-closing-odds'
    | '/api/public/hooks/crypto-study'
    | '/api/public/hooks/kalshi-book-tick'
    | '/api/public/hooks/market-context-tick'
    | '/api/public/hooks/market-intel-match'
    | '/api/public/hooks/martingale-tick'
    | '/api/public/hooks/multi-tf-shadow'
    | '/api/public/hooks/odds-shadow-tick'
    | '/api/public/hooks/ops-daily-backtest'
    | '/api/public/hooks/pin-risk-shadow-tick'
    | '/api/public/hooks/recompute-predictions'
    | '/api/public/hooks/settle-btc-predictions'
    | '/api/public/hooks/study-auto-live-tick'
    | '/api/public/hooks/study-lock-tick'
    | '/api/public/hooks/triple-window-tick'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ApiHealthKalshiRoute: typeof ApiHealthKalshiRoute
  ApiPublicSendDailyDigestsRoute: typeof ApiPublicSendDailyDigestsRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksAutoModelBetTickRoute: typeof ApiPublicHooksAutoModelBetTickRoute
  ApiPublicHooksAutoOddsTickRoute: typeof ApiPublicHooksAutoOddsTickRoute
  ApiPublicHooksAutoTradeRoute: typeof ApiPublicHooksAutoTradeRoute
  ApiPublicHooksBackfillOutcomesRoute: typeof ApiPublicHooksBackfillOutcomesRoute
  ApiPublicHooksBackfillTripleWindowRoute: typeof ApiPublicHooksBackfillTripleWindowRoute
  ApiPublicHooksBigFlipTickRoute: typeof ApiPublicHooksBigFlipTickRoute
  ApiPublicHooksBtcCalibrateRoute: typeof ApiPublicHooksBtcCalibrateRoute
  ApiPublicHooksBtcSnapshotTickRoute: typeof ApiPublicHooksBtcSnapshotTickRoute
  ApiPublicHooksCandlesIngestRoute: typeof ApiPublicHooksCandlesIngestRoute
  ApiPublicHooksCaptureClosingOddsRoute: typeof ApiPublicHooksCaptureClosingOddsRoute
  ApiPublicHooksCryptoStudyRoute: typeof ApiPublicHooksCryptoStudyRoute
  ApiPublicHooksKalshiBookTickRoute: typeof ApiPublicHooksKalshiBookTickRoute
  ApiPublicHooksMarketContextTickRoute: typeof ApiPublicHooksMarketContextTickRoute
  ApiPublicHooksMarketIntelMatchRoute: typeof ApiPublicHooksMarketIntelMatchRoute
  ApiPublicHooksMartingaleTickRoute: typeof ApiPublicHooksMartingaleTickRoute
  ApiPublicHooksMultiTfShadowRoute: typeof ApiPublicHooksMultiTfShadowRoute
  ApiPublicHooksOddsShadowTickRoute: typeof ApiPublicHooksOddsShadowTickRoute
  ApiPublicHooksOpsDailyBacktestRoute: typeof ApiPublicHooksOpsDailyBacktestRoute
  ApiPublicHooksPinRiskShadowTickRoute: typeof ApiPublicHooksPinRiskShadowTickRoute
  ApiPublicHooksRecomputePredictionsRoute: typeof ApiPublicHooksRecomputePredictionsRoute
  ApiPublicHooksSettleBtcPredictionsRoute: typeof ApiPublicHooksSettleBtcPredictionsRoute
  ApiPublicHooksStudyAutoLiveTickRoute: typeof ApiPublicHooksStudyAutoLiveTickRoute
  ApiPublicHooksStudyLockTickRoute: typeof ApiPublicHooksStudyLockTickRoute
  ApiPublicHooksTripleWindowTickRoute: typeof ApiPublicHooksTripleWindowTickRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analyze': {
      id: '/_authenticated/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AuthenticatedAnalyzeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/backtest': {
      id: '/_authenticated/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof AuthenticatedBacktestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chart': {
      id: '/_authenticated/chart'
      path: '/chart'
      fullPath: '/chart'
      preLoaderRoute: typeof AuthenticatedChartRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crypto': {
      id: '/_authenticated/crypto'
      path: '/crypto'
      fullPath: '/crypto'
      preLoaderRoute: typeof AuthenticatedCryptoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crypto-paper': {
      id: '/_authenticated/crypto-paper'
      path: '/crypto-paper'
      fullPath: '/crypto-paper'
      preLoaderRoute: typeof AuthenticatedCryptoPaperRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crypto-sandbox': {
      id: '/_authenticated/crypto-sandbox'
      path: '/crypto-sandbox'
      fullPath: '/crypto-sandbox'
      preLoaderRoute: typeof AuthenticatedCryptoSandboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/live': {
      id: '/_authenticated/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AuthenticatedLiveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/model-validation': {
      id: '/_authenticated/model-validation'
      path: '/model-validation'
      fullPath: '/model-validation'
      preLoaderRoute: typeof AuthenticatedModelValidationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ops-manual': {
      id: '/_authenticated/ops-manual'
      path: '/ops-manual'
      fullPath: '/ops-manual'
      preLoaderRoute: typeof AuthenticatedOpsManualRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pattern-performance': {
      id: '/_authenticated/pattern-performance'
      path: '/pattern-performance'
      fullPath: '/pattern-performance'
      preLoaderRoute: typeof AuthenticatedPatternPerformanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patterns': {
      id: '/_authenticated/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof AuthenticatedPatternsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/strategies': {
      id: '/_authenticated/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof AuthenticatedStrategiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analysis/$id': {
      id: '/_authenticated/analysis/$id'
      path: '/analysis/$id'
      fullPath: '/analysis/$id'
      preLoaderRoute: typeof AuthenticatedAnalysisIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/health/kalshi': {
      id: '/api/health/kalshi'
      path: '/api/health/kalshi'
      fullPath: '/api/health/kalshi'
      preLoaderRoute: typeof ApiHealthKalshiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-daily-digests': {
      id: '/api/public/send-daily-digests'
      path: '/api/public/send-daily-digests'
      fullPath: '/api/public/send-daily-digests'
      preLoaderRoute: typeof ApiPublicSendDailyDigestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-model-bet-tick': {
      id: '/api/public/hooks/auto-model-bet-tick'
      path: '/api/public/hooks/auto-model-bet-tick'
      fullPath: '/api/public/hooks/auto-model-bet-tick'
      preLoaderRoute: typeof ApiPublicHooksAutoModelBetTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-odds-tick': {
      id: '/api/public/hooks/auto-odds-tick'
      path: '/api/public/hooks/auto-odds-tick'
      fullPath: '/api/public/hooks/auto-odds-tick'
      preLoaderRoute: typeof ApiPublicHooksAutoOddsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-trade': {
      id: '/api/public/hooks/auto-trade'
      path: '/api/public/hooks/auto-trade'
      fullPath: '/api/public/hooks/auto-trade'
      preLoaderRoute: typeof ApiPublicHooksAutoTradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/backfill-outcomes': {
      id: '/api/public/hooks/backfill-outcomes'
      path: '/api/public/hooks/backfill-outcomes'
      fullPath: '/api/public/hooks/backfill-outcomes'
      preLoaderRoute: typeof ApiPublicHooksBackfillOutcomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/backfill-triple-window': {
      id: '/api/public/hooks/backfill-triple-window'
      path: '/api/public/hooks/backfill-triple-window'
      fullPath: '/api/public/hooks/backfill-triple-window'
      preLoaderRoute: typeof ApiPublicHooksBackfillTripleWindowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/big-flip-tick': {
      id: '/api/public/hooks/big-flip-tick'
      path: '/api/public/hooks/big-flip-tick'
      fullPath: '/api/public/hooks/big-flip-tick'
      preLoaderRoute: typeof ApiPublicHooksBigFlipTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/btc-calibrate': {
      id: '/api/public/hooks/btc-calibrate'
      path: '/api/public/hooks/btc-calibrate'
      fullPath: '/api/public/hooks/btc-calibrate'
      preLoaderRoute: typeof ApiPublicHooksBtcCalibrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/btc-snapshot-tick': {
      id: '/api/public/hooks/btc-snapshot-tick'
      path: '/api/public/hooks/btc-snapshot-tick'
      fullPath: '/api/public/hooks/btc-snapshot-tick'
      preLoaderRoute: typeof ApiPublicHooksBtcSnapshotTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/candles-ingest': {
      id: '/api/public/hooks/candles-ingest'
      path: '/api/public/hooks/candles-ingest'
      fullPath: '/api/public/hooks/candles-ingest'
      preLoaderRoute: typeof ApiPublicHooksCandlesIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/capture-closing-odds': {
      id: '/api/public/hooks/capture-closing-odds'
      path: '/api/public/hooks/capture-closing-odds'
      fullPath: '/api/public/hooks/capture-closing-odds'
      preLoaderRoute: typeof ApiPublicHooksCaptureClosingOddsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/crypto-study': {
      id: '/api/public/hooks/crypto-study'
      path: '/api/public/hooks/crypto-study'
      fullPath: '/api/public/hooks/crypto-study'
      preLoaderRoute: typeof ApiPublicHooksCryptoStudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/kalshi-book-tick': {
      id: '/api/public/hooks/kalshi-book-tick'
      path: '/api/public/hooks/kalshi-book-tick'
      fullPath: '/api/public/hooks/kalshi-book-tick'
      preLoaderRoute: typeof ApiPublicHooksKalshiBookTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/market-context-tick': {
      id: '/api/public/hooks/market-context-tick'
      path: '/api/public/hooks/market-context-tick'
      fullPath: '/api/public/hooks/market-context-tick'
      preLoaderRoute: typeof ApiPublicHooksMarketContextTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/market-intel-match': {
      id: '/api/public/hooks/market-intel-match'
      path: '/api/public/hooks/market-intel-match'
      fullPath: '/api/public/hooks/market-intel-match'
      preLoaderRoute: typeof ApiPublicHooksMarketIntelMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/martingale-tick': {
      id: '/api/public/hooks/martingale-tick'
      path: '/api/public/hooks/martingale-tick'
      fullPath: '/api/public/hooks/martingale-tick'
      preLoaderRoute: typeof ApiPublicHooksMartingaleTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/multi-tf-shadow': {
      id: '/api/public/hooks/multi-tf-shadow'
      path: '/api/public/hooks/multi-tf-shadow'
      fullPath: '/api/public/hooks/multi-tf-shadow'
      preLoaderRoute: typeof ApiPublicHooksMultiTfShadowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/odds-shadow-tick': {
      id: '/api/public/hooks/odds-shadow-tick'
      path: '/api/public/hooks/odds-shadow-tick'
      fullPath: '/api/public/hooks/odds-shadow-tick'
      preLoaderRoute: typeof ApiPublicHooksOddsShadowTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ops-daily-backtest': {
      id: '/api/public/hooks/ops-daily-backtest'
      path: '/api/public/hooks/ops-daily-backtest'
      fullPath: '/api/public/hooks/ops-daily-backtest'
      preLoaderRoute: typeof ApiPublicHooksOpsDailyBacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/pin-risk-shadow-tick': {
      id: '/api/public/hooks/pin-risk-shadow-tick'
      path: '/api/public/hooks/pin-risk-shadow-tick'
      fullPath: '/api/public/hooks/pin-risk-shadow-tick'
      preLoaderRoute: typeof ApiPublicHooksPinRiskShadowTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/recompute-predictions': {
      id: '/api/public/hooks/recompute-predictions'
      path: '/api/public/hooks/recompute-predictions'
      fullPath: '/api/public/hooks/recompute-predictions'
      preLoaderRoute: typeof ApiPublicHooksRecomputePredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/settle-btc-predictions': {
      id: '/api/public/hooks/settle-btc-predictions'
      path: '/api/public/hooks/settle-btc-predictions'
      fullPath: '/api/public/hooks/settle-btc-predictions'
      preLoaderRoute: typeof ApiPublicHooksSettleBtcPredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/study-auto-live-tick': {
      id: '/api/public/hooks/study-auto-live-tick'
      path: '/api/public/hooks/study-auto-live-tick'
      fullPath: '/api/public/hooks/study-auto-live-tick'
      preLoaderRoute: typeof ApiPublicHooksStudyAutoLiveTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/study-lock-tick': {
      id: '/api/public/hooks/study-lock-tick'
      path: '/api/public/hooks/study-lock-tick'
      fullPath: '/api/public/hooks/study-lock-tick'
      preLoaderRoute: typeof ApiPublicHooksStudyLockTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/triple-window-tick': {
      id: '/api/public/hooks/triple-window-tick'
      path: '/api/public/hooks/triple-window-tick'
      fullPath: '/api/public/hooks/triple-window-tick'
      preLoaderRoute: typeof ApiPublicHooksTripleWindowTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAnalyzeRoute: typeof AuthenticatedAnalyzeRoute
  AuthenticatedBacktestRoute: typeof AuthenticatedBacktestRoute
  AuthenticatedChartRoute: typeof AuthenticatedChartRoute
  AuthenticatedCryptoRoute: typeof AuthenticatedCryptoRoute
  AuthenticatedCryptoPaperRoute: typeof AuthenticatedCryptoPaperRoute
  AuthenticatedCryptoSandboxRoute: typeof AuthenticatedCryptoSandboxRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedLiveRoute: typeof AuthenticatedLiveRoute
  AuthenticatedModelValidationRoute: typeof AuthenticatedModelValidationRoute
  AuthenticatedOpsManualRoute: typeof AuthenticatedOpsManualRoute
  AuthenticatedPatternPerformanceRoute: typeof AuthenticatedPatternPerformanceRoute
  AuthenticatedPatternsRoute: typeof AuthenticatedPatternsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStrategiesRoute: typeof AuthenticatedStrategiesRoute
  AuthenticatedAnalysisIdRoute: typeof AuthenticatedAnalysisIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAnalyzeRoute: AuthenticatedAnalyzeRoute,
  AuthenticatedBacktestRoute: AuthenticatedBacktestRoute,
  AuthenticatedChartRoute: AuthenticatedChartRoute,
  AuthenticatedCryptoRoute: AuthenticatedCryptoRoute,
  AuthenticatedCryptoPaperRoute: AuthenticatedCryptoPaperRoute,
  AuthenticatedCryptoSandboxRoute: AuthenticatedCryptoSandboxRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedLiveRoute: AuthenticatedLiveRoute,
  AuthenticatedModelValidationRoute: AuthenticatedModelValidationRoute,
  AuthenticatedOpsManualRoute: AuthenticatedOpsManualRoute,
  AuthenticatedPatternPerformanceRoute: AuthenticatedPatternPerformanceRoute,
  AuthenticatedPatternsRoute: AuthenticatedPatternsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStrategiesRoute: AuthenticatedStrategiesRoute,
  AuthenticatedAnalysisIdRoute: AuthenticatedAnalysisIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ApiHealthKalshiRoute: ApiHealthKalshiRoute,
  ApiPublicSendDailyDigestsRoute: ApiPublicSendDailyDigestsRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksAutoModelBetTickRoute: ApiPublicHooksAutoModelBetTickRoute,
  ApiPublicHooksAutoOddsTickRoute: ApiPublicHooksAutoOddsTickRoute,
  ApiPublicHooksAutoTradeRoute: ApiPublicHooksAutoTradeRoute,
  ApiPublicHooksBackfillOutcomesRoute: ApiPublicHooksBackfillOutcomesRoute,
  ApiPublicHooksBackfillTripleWindowRoute:
    ApiPublicHooksBackfillTripleWindowRoute,
  ApiPublicHooksBigFlipTickRoute: ApiPublicHooksBigFlipTickRoute,
  ApiPublicHooksBtcCalibrateRoute: ApiPublicHooksBtcCalibrateRoute,
  ApiPublicHooksBtcSnapshotTickRoute: ApiPublicHooksBtcSnapshotTickRoute,
  ApiPublicHooksCandlesIngestRoute: ApiPublicHooksCandlesIngestRoute,
  ApiPublicHooksCaptureClosingOddsRoute: ApiPublicHooksCaptureClosingOddsRoute,
  ApiPublicHooksCryptoStudyRoute: ApiPublicHooksCryptoStudyRoute,
  ApiPublicHooksKalshiBookTickRoute: ApiPublicHooksKalshiBookTickRoute,
  ApiPublicHooksMarketContextTickRoute: ApiPublicHooksMarketContextTickRoute,
  ApiPublicHooksMarketIntelMatchRoute: ApiPublicHooksMarketIntelMatchRoute,
  ApiPublicHooksMartingaleTickRoute: ApiPublicHooksMartingaleTickRoute,
  ApiPublicHooksMultiTfShadowRoute: ApiPublicHooksMultiTfShadowRoute,
  ApiPublicHooksOddsShadowTickRoute: ApiPublicHooksOddsShadowTickRoute,
  ApiPublicHooksOpsDailyBacktestRoute: ApiPublicHooksOpsDailyBacktestRoute,
  ApiPublicHooksPinRiskShadowTickRoute: ApiPublicHooksPinRiskShadowTickRoute,
  ApiPublicHooksRecomputePredictionsRoute:
    ApiPublicHooksRecomputePredictionsRoute,
  ApiPublicHooksSettleBtcPredictionsRoute:
    ApiPublicHooksSettleBtcPredictionsRoute,
  ApiPublicHooksStudyAutoLiveTickRoute: ApiPublicHooksStudyAutoLiveTickRoute,
  ApiPublicHooksStudyLockTickRoute: ApiPublicHooksStudyLockTickRoute,
  ApiPublicHooksTripleWindowTickRoute: ApiPublicHooksTripleWindowTickRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
